"""Generate .github/workflows/build.yml and suggest.yml from options.py, so the dropdown labels in the
GitHub forms always match what the code expects. Run after editing options.py:  python src/make_workflows.py"""
import json, os
import options as O

q = json.dumps        # JSON strings are valid YAML double-quoted strings


def inp(name, desc, kind="string", default="", options=None):
    lines = [f"      {name}:", f"        description: {q(desc)}", f"        required: false"]
    if kind == "boolean":
        lines += ["        type: boolean", f"        default: {str(bool(default)).lower()}"]
    elif kind == "choice":
        lines += ["        type: choice", f"        default: {q(default)}", "        options:"] + [f"          - {q(o)}" for o in options]
    else:
        lines += [f"        default: {q(default)}"]
    return "\n".join(lines)


VIBE_HELP = " | ".join(f"{k.split(' (')[0]}: {v['blurb']}" for k, v in O.VIBES.items())
AVOID_HELP = ", ".join(sorted(O.AVOID_WORDS))

COMMON = [
    inp("vibe", "Deck vibe: the deck's personality (every vibe is Bracket 3). Mean vibes pick mean commanders. Applies even if you type a commander.",
        "choice", O.DEFAULT_VIBE, O.VIBE_LABELS),
    inp("colors", "Colors (exact color identity). Ignored if you type a commander.", "choice", O.ANY, O.COLOR_LABELS),
    inp("mechanical_theme", "Mechanical theme: how the deck plays.", "choice", O.ANY, O.MECH_LABELS),
    inp("narrative_theme", "Narrative theme: flavor and imagery (creature types, card names, rules and flavor text). A soft nudge.",
        "choice", O.ANY, O.NARR_LABELS),
    inp("tribe", "Creature type to emphasize (optional). Blank = tribal ONLY if the commander's own text references its type.", "string", ""),
]

BUILD_ONLY_TOP = [
    inp("randomize", "Surprise me: randomizes vibe, colors, and both themes (about 1 in 10 is a tribal deck whose tribe is the "
        "commander's own type). Anything you TYPE below is respected; the dropdowns above are ignored.", "boolean", False),
]
BUILD_ONLY_AFTER = [
    inp("pick_mode", "When Commander is blank: take the best match, or a random one from the top 10.", "choice", O.PICK_MODES[0], O.PICK_MODES),
    inp("commander", "Commander (optional, exact card name). Overrides the commander and colors dropdowns. Blank = pick one that fits.", "string", ""),
    inp("budget", "Approx USD budget for the nonland cards, max 500 (blank = 500). Lands never count: dual/shock/fetch lands are always included.", "string", ""),
    inp("must_include", "Cards to force in, separated by semicolons. Example: Sol Ring; Rhystic Study", "string", ""),
    inp("exclude", "Cards to leave out, separated by semicolons.", "string", ""),
    inp("avoid", "Things this deck must never include, comma separated. Options: " + AVOID_HELP, "string", ""),
    inp("seed", "Random seed (blank = new each time). Reuse a seed from a past run to reproduce a random result.", "string", ""),
    inp("big_spell", "Mana value of your biggest finisher (for the speed estimate).", "string", "8"),
]

HEAD = """on:
  workflow_dispatch:
    inputs:
"""

CACHE_AND_FETCH = """      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - id: day
        run: echo "d=$(date +%F)" >> "$GITHUB_OUTPUT"
      - uses: actions/cache@v4            # one Scryfall download per day, reused across runs
        with:
          path: data/cards.json
          key: cards-v3-${{ steps.day.outputs.d }}
      - name: Fetch Scryfall data (skipped if cached today)
        run: test -s data/cards.json || python src/fetch_cards.py
      - uses: actions/cache@v4            # Commander Spellbook combo database, once per day
        with:
          path: data/combos.json
          key: combos-v1-${{ steps.day.outputs.d }}
      - name: Fetch combo data from Commander Spellbook (skipped if cached today; never fails the run)
        run: test -s data/combos.json || python src/fetch_combos.py
"""

build = "\n".join([
    "name: Build and check a deck",
    "# GENERATED by src/make_workflows.py from src/options.py. Edit options.py and regenerate; don't hand-edit the choices.",
    "# Click \"Run workflow\", pick your options, then read the summary on the run page (or download the deck-report artifact).",
    HEAD.rstrip("\n"), *BUILD_ONLY_TOP, *COMMON, *BUILD_ONLY_AFTER,
]) + """
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RANDOMIZE: ${{ inputs.randomize }}
      VIBE: ${{ inputs.vibe }}
      COLORS: ${{ inputs.colors }}
      MECH: ${{ inputs.mechanical_theme }}
      NARR: ${{ inputs.narrative_theme }}
      TRIBE: ${{ inputs.tribe }}
      PICK_MODE: ${{ inputs.pick_mode }}
      COMMANDER: ${{ inputs.commander }}
      BUDGET: ${{ inputs.budget }}
      MUST: ${{ inputs.must_include }}
      EXCLUDE: ${{ inputs.exclude }}
      AVOID: ${{ inputs.avoid }}
      SEED: ${{ inputs.seed }}
      BIG: ${{ inputs.big_spell }}
    steps:
""" + CACHE_AND_FETCH + """      - name: Plan and build the deck
        run: >
          python src/build_deck.py --randomize "$RANDOMIZE" --vibe "$VIBE" --colors "$COLORS" --mech "$MECH"
          --narr "$NARR" --tribe "$TRIBE" --pick-mode "$PICK_MODE" --commander "$COMMANDER" --budget "$BUDGET"
          --must "$MUST" --exclude "$EXCLUDE" --avoid "$AVOID" --seed "$SEED"
      - name: Goldfish simulation
        # Uses the tribe the builder settled on (typed, auto-detected, or none), saved in out/tribe.txt.
        run: python src/goldfish.py out/deck.txt --tribe "$(cat out/tribe.txt)" --big-spell "$BIG"
      - name: Bracket report
        run: python src/bracket_report.py out/deck.txt --target "$(cat out/target.txt)"
      - name: Run summary
        if: always()
        run: python src/summarize.py >> "$GITHUB_STEP_SUMMARY"
      - uses: actions/upload-artifact@v4
        if: always()
        with: { name: deck-report, path: out/ }
"""

suggest = "\n".join([
    "name: Suggest commanders",
    "# GENERATED by src/make_workflows.py from src/options.py.",
    "# Pick vibe / colors / themes, run it, and read the ranked commander list on the run page.",
    "# Then type your favorite into the Commander box of \"Build and check a deck\".",
    HEAD.rstrip("\n"), *COMMON,
]) + """
jobs:
  suggest:
    runs-on: ubuntu-latest
    env:
      VIBE: ${{ inputs.vibe }}
      COLORS: ${{ inputs.colors }}
      MECH: ${{ inputs.mechanical_theme }}
      NARR: ${{ inputs.narrative_theme }}
      TRIBE: ${{ inputs.tribe }}
    steps:
""" + CACHE_AND_FETCH + """      - name: Find commanders that fit
        run: >
          python src/build_deck.py --suggest-only --vibe "$VIBE" --colors "$COLORS" --mech "$MECH"
          --narr "$NARR" --tribe "$TRIBE"
      - name: Run summary
        if: always()
        run: python src/summarize.py --suggest >> "$GITHUB_STEP_SUMMARY"
"""

if __name__ == "__main__":
    os.makedirs(".github/workflows", exist_ok=True)
    open(".github/workflows/build.yml", "w", encoding="utf-8").write(build)
    open(".github/workflows/suggest.yml", "w", encoding="utf-8").write(suggest)
    print("wrote .github/workflows/build.yml and suggest.yml")
